import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Starter from "../components/MainComponents.tsx/Starter"
import Navbar from "../components/MainComponents.tsx/Navbar"
import { CartProvider } from "./context/CartContext"
import { WishlistProvider } from "./context/WishlistContext"
import Footer from "@/components/MainComponents.tsx/Footer"
import { ClerkProvider } from "@clerk/nextjs"; 
import type React from "react" 
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // const { userId } = await auth()

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <CartProvider>
            <WishlistProvider>
              <Starter/>
              <Navbar />
              {children}
            </WishlistProvider>
          </CartProvider>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}

